/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChartRenderer: typeof import('./src/components/Echarts/components/ChartRenderer.vue')['default']
    DataTableRenderer: typeof import('./src/components/Echarts/components/DataTableRenderer.vue')['default']
    Echarts: typeof import('./src/components/Echarts/index.vue')['default']
    EchartsMap: typeof import('./src/components/echartsMap.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LinkedEcharts: typeof import('./src/components/LinkedEcharts/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreeJSMap: typeof import('./src/components/ThreeJSMap/index.vue')['default']
    Toolbar: typeof import('./src/components/LinkedEcharts/components/Toolbar.vue')['default']
    UnifiedTooltipRenderer: typeof import('./src/components/LinkedEcharts/components/UnifiedTooltipRenderer.vue')['default']
  }
}
